language: python
dist: bionic
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - sudo apt-get install libcurl4-openssl-dev
  - pip install -r requirements.txt
  - pip install pytest-benchmark
  - pip install codecov
  - pip install pytest-cov
script:
  - py.test --cov-report=xml --cov=lostruct tests/

after_success:
  - codecov